// Generated catalogue data for depot_suite.html.
// Prices are simulator unit prices, not supplier catalogue prices.
window.DEPOT_CATALOG_ITEMS = [
  {
    "id": "fitout-workbench",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Workbench",
    "imageKey": "workbench",
    "qtyBasis": "n_tech",
    "simulatorUnitPrice": 616,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan / Bott",
    "reference": "Bott Cubio Heavy Duty Workbench",
    "productUrl": "https://www.manutan.co.uk/en/key/heavy-duty-workbenches",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/heavy-duty-workbenches",
    "description": "Heavy-duty workshop benchmark from Manutan UK; discounted online list price visible on category page."
  },
  {
    "id": "fitout-workshop-stool",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Workshop stool",
    "imageKey": "workshop-stool",
    "qtyBasis": "n_tech",
    "simulatorUnitPrice": 120,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan Expert",
    "reference": "Assembly Lab Stool - PVC Seat - Tool Storage",
    "productUrl": "https://www.manutan.co.uk/en/key/chairs",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/chairs",
    "description": "Workshop/lab stool benchmark from Manutan UK chair range."
  },
  {
    "id": "fitout-locked-tool-cabinet",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Locked tool cabinet",
    "imageKey": "locked-tool-cabinet",
    "qtyBasis": "ceil(n_tech/2)",
    "simulatorUnitPrice": 620,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan Expert",
    "reference": "Tool cabinet - Manutan Expert",
    "productUrl": "https://www.manutan.co.uk/en/key/tool-cabinet-manutan",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/tool-cabinet-manutan",
    "description": "Tall lockable tool cabinet with bins and shelves."
  },
  {
    "id": "fitout-anti-fatigue-mat",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Anti-fatigue mat",
    "imageKey": "anti-fatigue-mat",
    "qtyBasis": "n_tech",
    "simulatorUnitPrice": 45,
    "simulatorAnnualRecurring": 15,
    "supplier": "Manutan / Coba",
    "reference": "Thick Foam Anti-fatigue Orthomat Mat",
    "productUrl": "https://www.manutan.co.uk/en/key/thick-foam-anti-fatigue-orthomat-mat",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/thick-foam-anti-fatigue-orthomat-mat",
    "description": "prorated replacement every 3 yrs Dry industrial anti-fatigue mat benchmark."
  },
  {
    "id": "fitout-workstation-task-lamp",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Workstation task lamp",
    "imageKey": "workstation-task-lamp",
    "qtyBasis": "n_tech",
    "simulatorUnitPrice": 85,
    "simulatorAnnualRecurring": 0,
    "supplier": "Krstlv / Lightsdaddy",
    "reference": "10X Magnifying Glass with Light, 5 color modes, dimmable LED desk lamp",
    "productUrl": "https://lightsdaddy.com/products/krstlv-10x-magnifying-glass-with-light-and-stand-5-color-modes-stepless-dimmable-led-lighted-desk-lamp-hands-free-flexible-goo",
    "priceSourceUrl": "https://lightsdaddy.com/products/krstlv-10x-magnifying-glass-with-light-and-stand-5-color-modes-stepless-dimmable-led-lighted-desk-lamp-hands-free-flexible-goo",
    "description": "Comparable magnifying LED task lamp for close work; simulator keeps a conservative procurement allowance."
  },
  {
    "id": "fitout-waste-sorting-bin-set",
    "module": "Fit-Out",
    "category": "Technical Workshop",
    "item": "Waste + sorting bin set",
    "imageKey": "waste-sorting-bin-set",
    "qtyBasis": "ceil(n_tech/4)",
    "simulatorUnitPrice": 95,
    "simulatorAnnualRecurring": 30,
    "supplier": "Probbax / Manutan",
    "reference": "Selective sorting bin - 60 l - Probbax (set)",
    "productUrl": "https://www.manutan.co.uk/en/key/selective-sorting-bin-60-l-probbax",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/selective-sorting-bin-60-l-probbax",
    "description": "bin bags & hazardous waste disposal/yr Set pricing captured directly from Manutan UK."
  },
  {
    "id": "fitout-integrated-esd-workstation-bench-lighting-power-rail-esd-kit-drawers-treston-concept-esd-lista-88-bott-cubio",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "Integrated ESD workstation — bench + lighting + power rail + ESD kit + drawers (Treston Concept ESD / Lista 88 / Bott Cubio)",
    "imageKey": "integrated-esd-workstation-bench-lighting-power-rail-esd-kit-drawers-treston-concept-esd-lista-88-bott-cubio",
    "qtyBasis": "n_bench",
    "simulatorUnitPrice": 3800,
    "simulatorAnnualRecurring": 0,
    "supplier": "Treston / RS",
    "reference": "TPH718 ESD workbench with shelf + NaturLite LED 900 + 0830 ESD cabinet + wrist strap set",
    "productUrl": "https://www.treston.com/esd-products/esd-workbenches",
    "priceSourceUrl": "https://uk.rs-online.com/web/p/workbenches/1357350",
    "description": "IEC 61340-5-1. 10-yr warranty typical. Annual ESD certification check recommended. Bundle benchmark built from current RS pricing for Treston ESD workbench with shelf, NaturLite LED task light, 8-drawer ESD cabinet, and a compliant wrist-strap grounding set. Power-rail content may still vary by final workstation layout."
  },
  {
    "id": "fitout-bench-instrument-pack-oscilloscope-100mhz-dual-dc-psu-dmm-keysight-rigol-tektronix-fluke",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "Bench instrument pack — oscilloscope ≥100MHz + dual DC PSU + DMM (Keysight / Rigol / Tektronix / Fluke)",
    "imageKey": "bench-instrument-pack-oscilloscope-100mhz-dual-dc-psu-dmm-keysight-rigol-tektronix-fluke",
    "qtyBasis": "n_bench",
    "simulatorUnitPrice": 2400,
    "simulatorAnnualRecurring": 120,
    "supplier": "RS PRO / Fluke",
    "reference": "Bundle: RS PRO RSDS1102CML+ 100MHz oscilloscope + RS PRO 2-output bench PSU + Fluke 179/EDA2 DMM kit",
    "productUrl": "https://uk.rs-online.com/web/p/oscilloscopes/1236437 | https://uk.rs-online.com/web/p/bench-power-supplies/1233612 | https://uk.rs-online.com/web/p/multimeter-kits/0237467",
    "priceSourceUrl": "https://uk.rs-online.com/web/p/oscilloscopes/1236437 | https://uk.rs-online.com/web/p/bench-power-supplies/1233612 | https://uk.rs-online.com/web/p/multimeter-kits/0237467",
    "description": "Annual calibration (ISO 17025) per station — mandatory for railway maintenance documentation Bundle price is the sum of RS PRO 100MHz oscilloscope GBP 526.79, RS PRO 2-output bench PSU GBP 479.44, and Fluke 179/EDA2 multimeter kit GBP 461.50."
  },
  {
    "id": "fitout-soldering-rework-station-esd-safe-iron-hot-air-rework-fume-extractor-weller-wx-jbc-hakko-fx-951",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "Soldering + rework station ESD-safe — iron + hot-air rework + fume extractor (Weller WX / JBC / Hakko FX-951)",
    "imageKey": "soldering-rework-station-esd-safe-iron-hot-air-rework-fume-extractor-weller-wx-jbc-hakko-fx-951",
    "qtyBasis": "n_bench",
    "simulatorUnitPrice": 680,
    "simulatorAnnualRecurring": 75,
    "supplier": "Weller / RS",
    "reference": "Bundle: Weller WXsmart T0053456699 digital rework station + Weller FT12 F7 solder fume extractor",
    "productUrl": "https://uk.rs-online.com/web/p/soldering-stations/2775840 | https://uk.rs-online.com/web/p/soldering-fume-extractors/1268834",
    "priceSourceUrl": "https://uk.rs-online.com/web/p/soldering-stations/2775840 | https://uk.rs-online.com/web/p/soldering-fume-extractors/1268834",
    "description": "Tips, solder wire, flux, fume filter cartridges/yr/station Bundle benchmark: Weller WXsmart T0053456699 digital ESD-safe rework station GBP 2,054.82 plus Weller FT12 F7 ESD-safe solder fume extractor GBP 486.72. This is a premium Weller benchmark and may exceed the simulator allowance."
  },
  {
    "id": "fitout-anti-static-vacuum-shared-nilfisk-uz934-esd-ruwac-ds1400",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "Anti-static vacuum (shared) — Nilfisk UZ934 ESD / Ruwac DS1400",
    "imageKey": "anti-static-vacuum-shared-nilfisk-uz934-esd-ruwac-ds1400",
    "qtyBasis": "1",
    "simulatorUnitPrice": 420,
    "simulatorAnnualRecurring": 50,
    "supplier": "Nilfisk / Euroclean",
    "reference": "UZ934 dry pick-up tank vacuum",
    "productUrl": "https://www.chicagoshopusa.com/The-Euroclean-UZ-934-and-UZ-934-HEPA-dry-pick-up-tank-vacuum_p_14166.html",
    "priceSourceUrl": "https://www.chicagoshopusa.com/The-Euroclean-UZ-934-and-UZ-934-HEPA-dry-pick-up-tank-vacuum_p_14166.html",
    "description": "HEPA filter replacement/yr Legacy UZ934 benchmark found on specialist vacuum reseller; US pricing only at this stage."
  },
  {
    "id": "fitout-ups-for-instrument-protection-1-per-3-stations",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "UPS for instrument protection (1 per 3 stations)",
    "imageKey": "ups-for-instrument-protection-1-per-3-stations",
    "qtyBasis": "ceil(n_bench/3)",
    "simulatorUnitPrice": 821,
    "simulatorAnnualRecurring": 55,
    "supplier": "APC / RS",
    "reference": "SMT1000IC Smart-UPS 1000VA",
    "productUrl": "https://uk.rs-online.com/web/p/uninterruptible-power-supplies/1880181",
    "priceSourceUrl": "https://uk.rs-online.com/web/p/uninterruptible-power-supplies/1880181",
    "description": "Battery replacement prorated/yr Tower Smart-UPS benchmark from RS; rack models are also available at higher price."
  },
  {
    "id": "fitout-3d-printer-shared-enclosed-fdm-unit-for-prototype-parts-and-maintenance-jigs",
    "module": "Fit-Out",
    "category": "Electronics Workshop",
    "item": "3D printer (shared enclosed FDM unit for prototype parts and maintenance jigs)",
    "imageKey": "3d-printer-shared-enclosed-fdm-unit-for-prototype-parts-and-maintenance-jigs",
    "qtyBasis": "1",
    "simulatorUnitPrice": 3200,
    "simulatorAnnualRecurring": 450,
    "supplier": "Bambu Lab",
    "reference": "X1 Carbon",
    "productUrl": "https://us.store.bambulab.com/products/x1-carbon",
    "priceSourceUrl": "https://us.store.bambulab.com/products/x1-carbon",
    "description": "Filament, spare nozzles, build plates, routine service and small replacement parts/yr Official Bambu Lab direct price captured on current US store page."
  },
  {
    "id": "fitout-desk",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Desk",
    "imageKey": "desk",
    "qtyBasis": "n_eng",
    "simulatorUnitPrice": 450,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Oxford Cantilever Straight Desk",
    "productUrl": "https://www.manutan.co.uk/en/key/office-desks",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/office-desks",
    "description": "General engineering-office desk benchmark."
  },
  {
    "id": "fitout-ergonomic-office-chair",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Ergonomic office chair",
    "imageKey": "ergonomic-office-chair",
    "qtyBasis": "n_eng",
    "simulatorUnitPrice": 280,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan Expert",
    "reference": "Tria office chair with fixed armrest - Ergonomic",
    "productUrl": "https://www.manutan.co.uk/en/key/ergonomic-office-chairs",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/ergonomic-office-chairs",
    "description": "Office ergonomic chair benchmark."
  },
  {
    "id": "fitout-dual-monitor-setup",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Dual monitor setup",
    "imageKey": "dual-monitor-setup",
    "qtyBasis": "n_eng",
    "simulatorUnitPrice": 380,
    "simulatorAnnualRecurring": 0,
    "supplier": "Dell",
    "reference": "Dell Pro 24 Plus Monitor P2425H (x2)",
    "productUrl": "https://www.dell.com/en-uk/shop/dell-24-monitor-p2425h/apd/210-bnsf/monitors-monitor-accessories",
    "priceSourceUrl": "https://www.dell.com/en-uk/shop/dell-24-monitor-p2425h/apd/210-bnsf/monitors-monitor-accessories",
    "description": "Unit price is per monitor; use x2 for the dual-monitor package."
  },
  {
    "id": "fitout-technical-document-cabinet",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Technical document cabinet",
    "imageKey": "technical-document-cabinet",
    "qtyBasis": "ceil(n_eng/3)",
    "simulatorUnitPrice": 350,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan Expert",
    "reference": "Metal Filing Cabinet For Suspension Files - Lockable - Emris",
    "productUrl": "https://www.manutan.co.uk/en/key/metal-filing-cabinet-for-suspension-files-lockable-manutan-emris-a158961",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/metal-filing-cabinet-for-suspension-files-lockable-manutan-emris-a158961",
    "description": "Exact lockable filing-cabinet product selected as the document-cabinet benchmark."
  },
  {
    "id": "fitout-whiteboard-wall-mounted",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Whiteboard (wall-mounted)",
    "imageKey": "whiteboard-wall-mounted",
    "qtyBasis": "1",
    "simulatorUnitPrice": 180,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan Expert",
    "reference": "Magnetic Wall Whiteboard - Erasable Surface",
    "productUrl": "https://www.manutan.co.uk/en/key/magnetic-wall-whiteboard-erasable-surface-various-sizes-manutan",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/magnetic-wall-whiteboard-erasable-surface-various-sizes-manutan",
    "description": "Entry whiteboard benchmark; ceramic boards are also available at higher cost."
  },
  {
    "id": "fitout-local-a3-printer",
    "module": "Fit-Out",
    "category": "Engineering Office",
    "item": "Local A3 printer",
    "imageKey": "local-a3-printer",
    "qtyBasis": "1",
    "simulatorUnitPrice": 420,
    "simulatorAnnualRecurring": 180,
    "supplier": "Brother",
    "reference": "MFC-J6540DW",
    "productUrl": "https://store.brother.co.uk/en-gb/devices/inkjet/mfcj/mfcj6540dw",
    "priceSourceUrl": "https://www.idealo.co.uk/compare/201898226/brother-mfc-j6540dw.html",
    "description": "toner + maintenance contract/yr Official product page plus market-price benchmark from UK price aggregator."
  },
  {
    "id": "fitout-executive-desk",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Executive desk",
    "imageKey": "executive-desk",
    "qtyBasis": "n_mgr",
    "simulatorUnitPrice": 550,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Regent Executive Straight Desk",
    "productUrl": "https://www.manutan.co.uk/en/key/regent-executive-straight-desk",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/regent-executive-straight-desk",
    "description": "Executive-straight-desk benchmark from Manutan UK."
  },
  {
    "id": "fitout-executive-chair",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Executive chair",
    "imageKey": "executive-chair",
    "qtyBasis": "n_mgr",
    "simulatorUnitPrice": 320,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Executive Office Chairs",
    "productUrl": "https://www.manutan.co.uk/en/key/executive-office-chairs",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/executive-office-chairs",
    "description": "Category benchmark from Manutan executive-office range."
  },
  {
    "id": "fitout-monitor",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Monitor",
    "imageKey": "monitor",
    "qtyBasis": "n_mgr",
    "simulatorUnitPrice": 280,
    "simulatorAnnualRecurring": 0,
    "supplier": "Dell",
    "reference": "UltraSharp 24 Monitor U2424H",
    "productUrl": "https://www.dell.com/en-uk/shop/dell-ultrasharp-24-monitor-u2424h/apd/210-bktz/",
    "priceSourceUrl": "https://www.dell.com/en-uk/shop/dell-ultrasharp-24-monitor-u2424h/apd/210-bktz/",
    "description": "Manager-office single-monitor benchmark."
  },
  {
    "id": "fitout-secured-filing-cabinet",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Secured filing cabinet",
    "imageKey": "secured-filing-cabinet",
    "qtyBasis": "n_mgr",
    "simulatorUnitPrice": 380,
    "simulatorAnnualRecurring": 0,
    "supplier": "Bisley / Manutan",
    "reference": "Bisley 4 Drawer Suspension Filing Cabinet - Lockable",
    "productUrl": "https://www.manutan.co.uk/en/key/bisley-4-drawer-suspension-filing-cabinet-lockable-office-storage",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/bisley-4-drawer-suspension-filing-cabinet-lockable-office-storage",
    "description": "Lockable four-drawer filing-cabinet benchmark from Manutan UK."
  },
  {
    "id": "fitout-meeting-table-6-chairs",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Meeting table + 6 chairs",
    "imageKey": "meeting-table-6-chairs",
    "qtyBasis": "1",
    "simulatorUnitPrice": 1200,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan / Sodematub",
    "reference": "Meeting table set with 4 tables and 6 chairs",
    "productUrl": "https://www.manutan.co.uk/en/key/meeting-table-set-with-4-tables-and-6-chairs",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/meeting-table-set-with-4-tables-and-6-chairs",
    "description": "Bundle benchmark from Manutan UK."
  },
  {
    "id": "fitout-datashow",
    "module": "Fit-Out",
    "category": "Management Office",
    "item": "Datashow",
    "imageKey": "datashow",
    "qtyBasis": "1",
    "simulatorUnitPrice": 1269,
    "simulatorAnnualRecurring": 80,
    "supplier": "Epson",
    "reference": "Epson EB-2250U Full HD",
    "productUrl": "https://www.epson.co.uk/en_GB/products/projector/portable/eb-2250u-projector/p/21004",
    "priceSourceUrl": "https://www.idealo.co.uk/compare/5342646/epson-eb-2250u.html",
    "description": "WUXGA (1920×1200) 3LCD business projector, 5 000 lm, lamp life 4 000 h standard / 7 000 h eco (ELPLP96). Meeting room and briefing use. Annual recurring: lamp prorated + filter/cleaning + annual service."
  },
  {
    "id": "fitout-mfc-printer-scanner-a3-colour",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "MFC printer/scanner A3 colour",
    "imageKey": "mfc-printer-scanner-a3-colour",
    "qtyBasis": "1",
    "simulatorUnitPrice": 1800,
    "simulatorAnnualRecurring": 400,
    "supplier": "Brother",
    "reference": "MFC-J6955DW",
    "productUrl": "https://www.printerland.co.uk/product/brother-mfc-j6955dw/151041",
    "priceSourceUrl": "https://pricespy.co.uk/product.php?p=6030115",
    "description": "toner + annual maintenance contract Market benchmark for A3 colour multifunction office printer."
  },
  {
    "id": "fitout-document-shredder",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "Document shredder",
    "imageKey": "document-shredder",
    "qtyBasis": "1",
    "simulatorUnitPrice": 280,
    "simulatorAnnualRecurring": 0,
    "supplier": "Fellowes / Manutan",
    "reference": "Fellowes LX70 Cross Cut Paper Shredder",
    "productUrl": "https://www.manutan.co.uk/en/key/fellowes-lx70-cross-cut-paper-shredder",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/fellowes-lx70-cross-cut-paper-shredder",
    "description": "Small-office shredding benchmark."
  },
  {
    "id": "fitout-archive-shelving-module",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "Archive shelving module",
    "imageKey": "archive-shelving-module",
    "qtyBasis": "n_arch",
    "simulatorUnitPrice": 180,
    "simulatorAnnualRecurring": 0,
    "supplier": "Rapid 2 / Manutan",
    "reference": "Rapid 2 Single Sided Lever Arch Storage Unit For 20 A4 Files",
    "productUrl": "https://www.manutan.co.uk/en/key/archive-shelving",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/archive-shelving",
    "description": "Archive shelving/document storage benchmark."
  },
  {
    "id": "fitout-depot-info-display-screen",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "Depot info display screen",
    "imageKey": "depot-info-display-screen",
    "qtyBasis": "n_screens",
    "simulatorUnitPrice": 580,
    "simulatorAnnualRecurring": 0,
    "supplier": "Samsung",
    "reference": "QM55C 55-inch professional display",
    "productUrl": "https://www.samsung.com/uk/smart-signage/uhd-4k-signage/qmb-55-inch-lh55qmbebgcxen/",
    "priceSourceUrl": "https://pricespy.co.uk/product.php?p=12548154",
    "description": "Professional signage/display benchmark."
  },
  {
    "id": "fitout-water-dispenser-bottle-type",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "Water dispenser (bottle type)",
    "imageKey": "water-dispenser-bottle-type",
    "qtyBasis": "n_water",
    "simulatorUnitPrice": 350,
    "simulatorAnnualRecurring": 480,
    "supplier": "Manutan Expert",
    "reference": "Hot, cold and room temperature water dispenser",
    "productUrl": "https://www.manutan.co.uk/en/key/hot-cold-and-room-temperature-water-dispenser-manutan",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/hot-cold-and-room-temperature-water-dispenser-manutan",
    "description": "bottle delivery contract/yr per unit Current Manutan UK price captured directly on product page."
  },
  {
    "id": "fitout-coffee-machine",
    "module": "Fit-Out",
    "category": "Common Areas",
    "item": "Coffee machine",
    "imageKey": "coffee-machine",
    "qtyBasis": "1",
    "simulatorUnitPrice": 380,
    "simulatorAnnualRecurring": 240,
    "supplier": "De'Longhi",
    "reference": "Magnifica S ECAM 22.110 / 22.115",
    "productUrl": "https://www.delonghi.com/en-gb/p/magnifica-magnifica-bean-to-cup-coffee-machine-esam4200.s/ESAM4200.S%2BEX%253A1.html",
    "priceSourceUrl": "https://pricespy.co.uk/home-garden/kitchen-household/coffee-machines/espresso-machines/delonghi-magnifica-s-ecam-22.110--p1641244",
    "description": "coffee pods + descaling/yr Entry bean-to-cup office coffee benchmark."
  },
  {
    "id": "fitout-personal-locker-vestiaire",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "Personal locker (vestiaire)",
    "imageKey": "personal-locker-vestiaire",
    "qtyBasis": "n_tech+n_eng",
    "simulatorUnitPrice": 264,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Standard storage lockers / clothes lockers",
    "productUrl": "https://www.manutan.co.uk/en/key/standard-storage-lockers",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/standard-storage-lockers",
    "description": "Single-compartment personal locker benchmark from Manutan UK."
  },
  {
    "id": "fitout-locker-room-bench",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "Locker room bench",
    "imageKey": "locker-room-bench",
    "qtyBasis": "ceil((n_tech+n_eng)/5)",
    "simulatorUnitPrice": 339,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Single-Sided Cloakroom/Changing Room Bench",
    "productUrl": "https://www.manutan.co.uk/en/key/single-sided-benches",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/single-sided-benches",
    "description": "Robust locker-room/changing-room bench benchmark."
  },
  {
    "id": "fitout-industrial-washing-machine",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "Industrial washing machine",
    "imageKey": "industrial-washing-machine",
    "qtyBasis": "n_wash",
    "simulatorUnitPrice": 2400,
    "simulatorAnnualRecurring": 380,
    "supplier": "Electrolux Professional",
    "reference": "myPRO WE170P / WE170V 8kg commercial washer",
    "productUrl": "https://www.electroluxprofessional.com/en-my/commercial-laundry-equipment/mypro-washers-dryers-steam-ironers/",
    "priceSourceUrl": "https://www.buzzcateringsupplies.com/electrolux-mypro-washing-machine-8kg.html",
    "description": "maintenance + detergent/yr per machine myPRO washer benchmark captured on current reseller listing; reference family confirmed on Electrolux Professional."
  },
  {
    "id": "fitout-industrial-dryer",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "Industrial dryer",
    "imageKey": "industrial-dryer",
    "qtyBasis": "n_dry",
    "simulatorUnitPrice": 1800,
    "simulatorAnnualRecurring": 280,
    "supplier": "Electrolux Professional",
    "reference": "myPRO TE1120HP 8kg professional heat pump tumble dryer",
    "productUrl": "https://www.electroluxprofessional.com/en-my/commercial-laundry-equipment/mypro-washers-dryers-steam-ironers/",
    "priceSourceUrl": "https://www.appliancesdirect.co.uk/p/te1120hp/electrolux-professional-te1120hp---heat-pump-tumble-dryer",
    "description": "maintenance/yr per machine Current UK online price captured for the heat-pump variant; condenser versions may price differently."
  },
  {
    "id": "fitout-boot-dryer-rack",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "Boot dryer rack",
    "imageKey": "boot-dryer-rack",
    "qtyBasis": "1",
    "simulatorUnitPrice": 280,
    "simulatorAnnualRecurring": 0,
    "supplier": "Teknomek",
    "reference": "Boot dryer single sided",
    "productUrl": "https://teknomek.co.uk/collections/boot-dryers",
    "priceSourceUrl": "https://teknomek.co.uk/collections/boot-dryers",
    "description": "Industrial heated boot dryer rack benchmark from Teknomek."
  },
  {
    "id": "fitout-ppe-storage-cabinet",
    "module": "Fit-Out",
    "category": "Locker Room",
    "item": "PPE storage cabinet",
    "imageKey": "ppe-storage-cabinet",
    "qtyBasis": "ceil(n_tech/5)",
    "simulatorUnitPrice": 320,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan",
    "reference": "Clean & Dirty Locker - Wide Metal Single Cabinet",
    "productUrl": "https://www.manutan.co.uk/en/key/clean-dirty-locker-wide-metal-single-cabinet-3-year-guarantee",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/clean-dirty-locker-wide-metal-single-cabinet-3-year-guarantee",
    "description": "Clean/dirty garment cabinet used as PPE storage benchmark."
  },
  {
    "id": "fitout-fire-extinguisher",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Fire extinguisher",
    "imageKey": "fire-extinguisher",
    "qtyBasis": "n_extg",
    "simulatorUnitPrice": 85,
    "simulatorAnnualRecurring": 25,
    "supplier": "Seton",
    "reference": "6Kg ABC Powder Extinguisher Kit",
    "productUrl": "https://www.seton.co.uk/abc-powder-fire-extinguisher-kits.html",
    "priceSourceUrl": "https://www.seton.co.uk/abc-powder-fire-extinguisher-kits.html",
    "description": "annual inspection/unit Warehouse/factory ABC powder kit benchmark."
  },
  {
    "id": "fitout-first-aid-kit",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "First aid kit",
    "imageKey": "first-aid-kit",
    "qtyBasis": "n_firstaid",
    "simulatorUnitPrice": 120,
    "simulatorAnnualRecurring": 60,
    "supplier": "Seton",
    "reference": "British Standard First Aid Kit",
    "productUrl": "https://www.seton.co.uk/first-aid-supplies/first-aid-kits/workplace-first-aid-kits",
    "priceSourceUrl": "https://www.seton.co.uk/first-aid-supplies/first-aid-kits/workplace-first-aid-kits",
    "description": "annual restocking/kit Workplace first-aid kit benchmark from Seton."
  },
  {
    "id": "fitout-eye-wash-station",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Eye wash station",
    "imageKey": "eye-wash-station",
    "qtyBasis": "1",
    "simulatorUnitPrice": 380,
    "simulatorAnnualRecurring": 0,
    "supplier": "Haws",
    "reference": "7461 AXION green PC freestanding eyewash with powder-coated finish",
    "productUrl": "https://www.haws.ch/en-gb/products/7461-axion-green-pc-freestanding-eyewash-with-powder-coatimg/",
    "priceSourceUrl": "https://www.hawsco.com/wp-content/uploads/2023/11/2024_Haws-Product-Price-List_-Online.pdf",
    "description": "Industrial freestanding eyewash benchmark. Haws EMEA product page is request-for-quote; price benchmark uses Haws 2024 US list for comparable 7361-7461 AXION MSR pedestal eyewash. Complies with EN 15154-2 and ANSI Z358.1."
  },
  {
    "id": "fitout-defibrillator-aed",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Defibrillator (AED)",
    "imageKey": "defibrillator-aed",
    "qtyBasis": "1",
    "simulatorUnitPrice": 1800,
    "simulatorAnnualRecurring": 120,
    "supplier": "Seton / ZOLL",
    "reference": "ZOLL AED 3",
    "productUrl": "https://www.seton.co.uk/first-aid-supplies/aeds-and-resuscitation-equipment/defibrillators",
    "priceSourceUrl": "https://www.seton.co.uk/first-aid-supplies/aeds-and-resuscitation-equipment/defibrillators",
    "description": "annual maintenance + electrode pads Workplace AED benchmark from Seton."
  },
  {
    "id": "fitout-hazardous-materials-cabinet",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Hazardous materials cabinet",
    "imageKey": "hazardous-materials-cabinet",
    "qtyBasis": "1",
    "simulatorUnitPrice": 850,
    "simulatorAnnualRecurring": 0,
    "supplier": "Seton",
    "reference": "Dangerous & Flammable Substance COSHH Storage Cabinet",
    "productUrl": "https://www.seton.co.uk/dangerous-flammable-substance-storage-cabinets.html",
    "priceSourceUrl": "https://www.seton.co.uk/dangerous-flammable-substance-storage-cabinets.html",
    "description": "ATEX-rated, chemical storage Entry COSHH hazardous-storage cabinet benchmark."
  },
  {
    "id": "fitout-bunded-spill-pallet-for-oil-drums",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Bunded spill pallet for oil drums",
    "imageKey": "bunded-spill-pallet-for-oil-drums",
    "qtyBasis": "1",
    "simulatorUnitPrice": 251,
    "simulatorAnnualRecurring": 0,
    "supplier": "First Mats",
    "reference": "4-Drum Low-Profile Bunded Spill Pallet",
    "productUrl": "https://www.firstmats.co.uk/products/4-drum-230ltr-bunded-spill-pallet",
    "priceSourceUrl": "https://www.firstmats.co.uk/products/4-drum-230ltr-bunded-spill-pallet",
    "description": "Secondary containment pallet for oil or chemical drums; 4-drum HDPE benchmark with approx. 230 L sump capacity. HDPE secondary-containment spill pallet for up to four 205 L oil or chemical drums; approx. 230 L sump capacity and 1250 kg load benchmark."
  },
  {
    "id": "fitout-emergency-safety-shower",
    "module": "Fit-Out",
    "category": "Safety & Emergency",
    "item": "Emergency safety shower",
    "imageKey": "emergency-safety-shower",
    "qtyBasis": "1",
    "simulatorUnitPrice": 680,
    "simulatorAnnualRecurring": 0,
    "supplier": "Seton / Hughes",
    "reference": "Wall-Mounted Emergency Safety Shower",
    "productUrl": "https://www.seton.co.uk/first-aid-supplies/eye-wash-emergency-showers/safety-showers",
    "priceSourceUrl": "https://www.seton.co.uk/first-aid-supplies/eye-wash-emergency-showers/safety-showers",
    "description": "Compact emergency shower benchmark; combination shower options are higher."
  },
  {
    "id": "fitout-manual-pallet-truck-hand-pump",
    "module": "Fit-Out",
    "category": "Warehouse Equipment",
    "item": "Manual pallet truck (hand pump)",
    "imageKey": "manual-pallet-truck-hand-pump",
    "qtyBasis": "n_ptruck_m",
    "simulatorUnitPrice": 680,
    "simulatorAnnualRecurring": 40,
    "supplier": "Jungheinrich",
    "reference": "AM 20 hand pallet truck",
    "productUrl": "https://www.jungheinrich-profishop.co.uk/p/jungheinrich-am-20-hand-pallet-truck-with-standard-forks-98948-197092/",
    "priceSourceUrl": "https://www.jungheinrich-profishop.co.uk/p/jungheinrich-am-20-hand-pallet-truck-with-standard-forks-98948-197092/",
    "description": "Annual service (seals, pump, wheels) per unit. Ref: Jungheinrich AM 22 / Crown PTH 50 / Toyota BT Lifter Standard manual pallet truck benchmark."
  },
  {
    "id": "fitout-electric-walkie-pallet-truck",
    "module": "Fit-Out",
    "category": "Warehouse Equipment",
    "item": "Electric walkie pallet truck",
    "imageKey": "electric-walkie-pallet-truck",
    "qtyBasis": "n_ptruck_e",
    "simulatorUnitPrice": 7270,
    "simulatorAnnualRecurring": 380,
    "supplier": "Jungheinrich",
    "reference": "EJE 116i electric pallet truck",
    "productUrl": "https://www.jungheinrich-profishop.co.uk/p/jungheinrich-eje-116i-electric-pallet-truck-1219958-601302/",
    "priceSourceUrl": "https://www.jungheinrich-profishop.co.uk/p/jungheinrich-eje-116i-electric-pallet-truck-1219958-601302/",
    "description": "Annual service + battery maintenance per unit. Ref: Jungheinrich EJE 120 / Crown WP 3000 / Toyota LWE160 Lithium-ion walkie pallet truck with integrated charger."
  },
  {
    "id": "fitout-pallet-truck-battery-charger",
    "module": "Fit-Out",
    "category": "Warehouse Equipment",
    "item": "Pallet truck battery charger",
    "imageKey": "pallet-truck-battery-charger",
    "qtyBasis": "n_ptruck_e",
    "simulatorUnitPrice": 60,
    "simulatorAnnualRecurring": 0,
    "supplier": "AntOn by Jungheinrich",
    "reference": "Charger for PTL 1.5 electric pallet truck",
    "productUrl": "https://www.jungheinrich-profishop.co.uk/p/charger-for-anton-by-jungheinrich-electric-pallet-truck-ptl-15-1249649-603307/",
    "priceSourceUrl": "https://www.jungheinrich-profishop.co.uk/p/charger-for-anton-by-jungheinrich-electric-pallet-truck-ptl-15-1249649-603307/",
    "description": "External or spare charger per electric truck when not covered by the integrated charger Most modern walkie trucks ship with integrated chargers; this is a spare/external charger benchmark."
  },
  {
    "id": "fitout-weighing-pallet-truck-for-goods-receiving",
    "module": "Fit-Out",
    "category": "Warehouse Equipment",
    "item": "Weighing pallet truck for goods receiving",
    "imageKey": "weighing-pallet-truck-for-goods-receiving",
    "qtyBasis": "1",
    "simulatorUnitPrice": 1427,
    "simulatorAnnualRecurring": 55,
    "supplier": "Ameise / Jungheinrich",
    "reference": "PTM 2.0 Scale weighing pallet truck",
    "productUrl": "https://www.jungheinrich-profishop.co.uk/p/ameise-ptm-20-scale-weighing-pallet-truck-featuring-display-on-tiller-head-1101738-484565/",
    "priceSourceUrl": "https://www.jungheinrich-profishop.co.uk/p/ameise-ptm-20-scale-weighing-pallet-truck-featuring-display-on-tiller-head-1101738-484565/",
    "description": "Annual legal-metrology calibration. Optional receiving tool; can replace one standard manual pallet truck if the total fleet must stay fixed. Manual weighing pallet truck benchmark for goods receiving. Can replace one standard manual pallet truck if the project keeps a fixed pallet-truck fleet count."
  },
  {
    "id": "store-pallet-rack-bays",
    "module": "Store",
    "category": "Store Equipment",
    "item": "Pallet rack bays",
    "imageKey": "pallet-rack-bays",
    "qtyBasis": "Calculated bays from pallet positions and levels",
    "simulatorUnitPrice": 600,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan / Rapid Racking",
    "reference": "Rapid Pallet Racking complete kit",
    "productUrl": "https://www.manutan.co.uk/en/key/two-level-pallet-racking-kits-2700w-x-900d-",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/two-level-pallet-racking-kits-2700w-x-900d-",
    "description": "Pallet-rack bay benchmark. Geometry depends on pallet size, clearances, bay depth and number of storage levels. Complete pallet-racking kit benchmark from Manutan UK; RFQ should normalize to the project bay geometry."
  },
  {
    "id": "store-shelving-modules",
    "module": "Store",
    "category": "Store Equipment",
    "item": "Shelving modules",
    "imageKey": "shelving-modules",
    "qtyBasis": "Calculated modules from shelving storage area and module footprint",
    "simulatorUnitPrice": 175,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan / Rapid",
    "reference": "Long Span Shelving Kits - up to 1100kg per shelf",
    "productUrl": "https://www.manutan.co.uk/en/key/long-span-shelving-kits-a470106",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/two-level-pallet-racking-kits-2700w-x-900d-",
    "description": "Shelving module benchmark for boxes, light spares and consumables. Geometry depends on shelf depth, width and number of levels. Starter shelving-kit benchmark from Manutan UK; final RFQ should align width, depth and shelf-count to simulator geometry."
  },
  {
    "id": "store-cantilever-bays",
    "module": "Store",
    "category": "Store Equipment",
    "item": "Cantilever bays",
    "imageKey": "cantilever-bays",
    "qtyBasis": "Calculated bays from long-item storage area and arm geometry",
    "simulatorUnitPrice": 390,
    "simulatorAnnualRecurring": 0,
    "supplier": "Manutan / Rapid Racking",
    "reference": "Heavy Duty Cantilever Racking",
    "productUrl": "https://www.manutan.co.uk/en/key/heavy-duty-cantilever-racking-5000h-x-1200w",
    "priceSourceUrl": "https://www.manutan.co.uk/en/key/heavy-duty-cantilever-racking-5000h-x-1200w",
    "description": "Cantilever-bay benchmark for long or bulky items. Geometry depends on arm length, column height, arm levels and bay pitch. Starter-bay benchmark; verify bay width and arm count against store assumptions."
  }
];
